#!/bin/bash -e
curl -H 'Content-Type: application/x-ndjson' -X PUT '<username>:<password>@<localhost>:<port>/<index>/_bulk?pretty' -d '
{
  "mappings" : {
  "eachGame" : {
   "properties" : {
      "gameID_opponent": {"type": "text", "fielddata":true},
"-30 < x <= -25": {"type": "double"},
"5 < x <= 10": {"type": "double"},
"35 < x <= 40": {"type": "double"},
"10 < x <= 15": {"type": "double"},
"-25 < x <= -20": {"type": "double"},
"25 < x <= 30": {"type": "double"},
"-10 < x <= -5": {"type": "double"},
"15 < x <= 20": {"type": "double"},
"30 < x <= 35": {"type": "double"},
"20 < x <= 25": {"type": "double"},
"-5 < x <= 0": {"type": "double"},
"0 < x <= 5": {"type": "double"},
"-15 < x <= -10": {"type": "double"},
"<= -40": {"type": "double"},
"-35 < x <= -30": {"type": "double"},
"-20 < x <= -15": {"type": "double"},
"> 40": {"type": "double"},
"-40 < x <= -35": {"type": "double"},
"> 40 +": {"type": "double"},
"> 40 -": {"type": "double"},
"5 < x <= 10 +": {"type": "double"},
"-15 < x <= -10 +": {"type": "double"},
"<= -40 +": {"type": "double"},
"<= -40 -": {"type": "double"},
"-15 < x <= -10 -": {"type": "double"},
"-30 < x <= -25 -": {"type": "double"},
"30 < x <= 35 +": {"type": "double"},
"-30 < x <= -25 +": {"type": "double"},
"35 < x <= 40 +": {"type": "double"},
"25 < x <= 30 +": {"type": "double"},
"10 < x <= 15 -": {"type": "double"},
"25 < x <= 30 -": {"type": "double"},
"10 < x <= 15 +": {"type": "double"},
"20 < x <= 25 -": {"type": "double"},
"-25 < x <= -20 +": {"type": "double"},
"-25 < x <= -20 -": {"type": "double"},
"20 < x <= 25 +": {"type": "double"},
"0 < x <= 5 -": {"type": "double"},
"-10 < x <= -5 +": {"type": "double"},
"-10 < x <= -5 -": {"type": "double"},
"0 < x <= 5 +": {"type": "double"},
"35 < x <= 40 -": {"type": "double"},
"-40 < x <= -35 +": {"type": "double"},
"-40 < x <= -35 -": {"type": "double"},
"15 < x <= 20 +": {"type": "double"},
"15 < x <= 20 -": {"type": "double"},
"-35 < x <= -30 -": {"type": "double"},
"5 < x <= 10 -": {"type": "double"},
"-35 < x <= -30 +": {"type": "double"},
"-20 < x <= -15 -": {"type": "double"},
"-5 < x <= 0 -": {"type": "double"},
"-20 < x <= -15 +": {"type": "double"},
"-5 < x <= 0 +": {"type": "double"},
"30 < x <= 35 -": {"type": "double"},
"Total_+_%": {"type": "double"},
"Total_-_%": {"type": "double"},
"W/L": {"type": "text", "fielddata":true}
}
}
}
}'
